CREATE TABLE reservas (
ID SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
IDLIVRO INT NOT NULL);

CREATE TABLE livros (
ID SERIAL PRIMARY KEY  NOT NULL,
NOME VARCHAR(30) NOT NULL,
RESERVADO VARCHAR(30) NOT NULL);

CREATE TABLE chamada (
ID SERIAL PRIMARY KEY  NOT NULL,
SALA VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL);

CREATE TABLE chamada (
ID SERIAL PRIMARY KEY  NOT NULL,
SALA VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
DIA timestamp with time zone);

CREATE TABLE chamada (
ID SERIAL PRIMARY KEY  NOT NULL,
SALA VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
DIA DATE DEFAULT CURRENT_DATE);

CREATE TABLE chamada (
ID SERIAL PRIMARY KEY  NOT NULL,
SALA VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
DIA DATE DEFAULT NOW());

CREATE TABLE chamada (
ID SERIAL PRIMARY KEY  NOT NULL,
SALA VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
DIA timestamptz);